contactList/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('user_registration.urls')),
    path('api-auth/', include('rest_framework.urls')),
    path('api/dj-rest-auth/', include('dj_rest_auth.urls')),
    path('api/dj-rest-auth/registration/', include('dj_rest_auth.registration.urls')),
    path('api/', include('myApp.api_urls', namespace='api')),
    path('', include('myApp.urls', namespace='myApp')),
    
]

myApp/urls.py
from django.urls import path
from . import views

app_name = 'myApp'

urlpatterns = [
    path('contact_edit/<int:pk>/', views.EditContactView.as_view(), name='edit_contact'),
    path('delete_contact/<int:pk>/', views.ContactDeleteView.as_view(), name='delete_contact'),
    path('contact_list/export',views.export_to_csv, name='export_contacts'),
    path('contact_list/import',views.import_from_csv, name='import_contacts'),
    path('contact_list/',views.ContactListView.as_view(), name='contact_list'),
    path('add_contact/', views.AddContactView.as_view(), name='add_contact'),
    path('', views.IndexView.as_view(), name='home'),
    path('authorize/', views.authorize, name='authorize'),
    path('oauth2callback/', views.oauth2callback, name='oauth2callback'),
    path('google_contacts/', views.get_google_contacts, name='google_contacts'),
    path('google_contacts/add_from_google/<str:pk>/', views.add_contact_from_google, name='add_from_google'),
    path('contact_list/add_contact_in_google/<int:pk>/', views.add_contact_in_google, name='add_contact_in_google'),
]

myApp/models.py
from django.db import models
from django.contrib.auth.models import User
from phonenumber_field.modelfields import PhoneNumberField


class Contact(models.Model):
    name = models.CharField(max_length=200)
    phone_number = PhoneNumberField(region='TR')
    email = models.EmailField()
    address = models.CharField(max_length=264)
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.name
  
  
class GoogleAuth(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    access_token = models.TextField()
    refresh_token = models.TextField()
    token_uri = models.TextField()
    client_id = models.TextField()
    client_secret = models.TextField()
    scopes = models.TextField()
    expiry = models.DateTimeField()

    
class OAuthState(models.Model):
    state = models.CharField(max_length=255, unique=True)
    created = models.DateTimeField(auto_now_add=True)
    temp_user_token = models.CharField(max_length=255, blank=True, null=True)

myApp/forms.py
from django import forms
from .models import Contact


class ContactForm(forms.ModelForm):
  class Meta:
    model = Contact
    fields = ['name', 'phone_number', 'email', 'address']


class SearchForm(forms.Form):
  search_body = forms.CharField(max_length=264, label='Search')
  
  def __init__(self, *args, **kwargs):
      super().__init__(*args, **kwargs)
      self.fields['search_body'].widget.attrs['placeholder'] = 'Name, number, address, ...'
  
  
  

myApp/views.py
from django.urls import reverse_lazy
from django.shortcuts import redirect, render, get_object_or_404
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.db.models import Q
from django.contrib import messages
from django.urls import reverse
from django.http import JsonResponse, HttpResponseRedirect
from django.http import HttpResponse

from .models import Contact, GoogleAuth, OAuthState
from .forms import ContactForm, SearchForm
from .google import get_google_flow

import csv, os, datetime, secrets
from io import TextIOWrapper

from googleapiclient.discovery import build
from google.oauth2.credentials import Credentials


os.environ['OAUTHLIB_INSECURE_TRANSPORT'] = '1'
REDIRECT_URI = 'http://localhost:8000/oauth2callback/'


class IndexView(generic.TemplateView):
    template_name = "myApp/index.html"


class ContactListView(LoginRequiredMixin, generic.ListView):
    model = Contact
    context_object_name = 'contacts'
    template_name = "myApp/contact_list.html"

    def get_queryset(self):
        query_set = Contact.objects.filter(author=self.request.user)
        querry = self.request.GET.get('search_body')
        if querry:
            query_set = query_set.filter(Q(name__icontains=querry) |
                                         Q(phone_number__icontains=querry) |
                                         Q(email__icontains=querry) |
                                         Q(address__icontains=querry))
        return query_set

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = SearchForm(self.request.GET or None)
        return context


class AddContactView(LoginRequiredMixin, generic.CreateView):
    model = Contact
    form_class = ContactForm
    template_name = "myApp/add_contact.html"
    success_url = reverse_lazy('myApp:contact_list')

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class EditContactView(LoginRequiredMixin, UserPassesTestMixin, generic.UpdateView):
    model = Contact
    form_class = ContactForm
    template_name = "myApp/edit_contact.html"
    success_url = reverse_lazy('myApp:contact_list')

    def test_func(self):
        obj = self.get_object()
        return obj.author == self.request.user


class ContactDeleteView(LoginRequiredMixin, UserPassesTestMixin, generic.DeleteView):
    model = Contact
    template_name = "myApp/delete_contact.html"
    success_url = reverse_lazy('myApp:contact_list')

    def test_func(self):
        obj = self.get_object()
        return obj.author == self.request.user


# -----------EXPORT AND IMPORT-------------

def export_to_csv(request):
    '''Export all the user's contacts to a csv file.'''
    export_now(request.user)
    return redirect('myApp:contact_list')


def export_now(user):
    contacts = Contact.objects.filter(author=user)
    file_path = get_export_file_path(user)
    try:
        with open(file_path, 'w', newline='', encoding='utf-8') as file:
            writer = csv.DictWriter(file, fieldnames=['name', 'phone_number', 'email', 'address'])
            writer.writeheader()
            for contact in contacts:
                contacts_dic = {
                    'name':contact.name,
                    'phone_number': contact.phone_number,
                    'email': contact.email,
                    'address': contact.address,
                }
                writer.writerow(contacts_dic)
    except Exception as e:
        print(f"CSV export failed: {e}")
    return file_path


def get_export_file_path(user):
    '''
    Create a folder path and file name base on user's name and date.
    '''
    folder = os.path.join('contact_exports', user.username)
    os.makedirs(folder, exist_ok=True)
    filename = f"contacts_{datetime.datetime.now().strftime('%Y-%m-%d_%H-%M-%S')}.csv"
    return os.path.join(folder, filename)


def import_from_csv(request):
    if request.method == "POST":
        uploaded_file = request.FILES.get('my_file')
        if not uploaded_file or not uploaded_file.name.endswith('.csv'):
            messages.warning(request, 'Please upload a valid CSV file.')
            return redirect('myApp:contact_list')
        import_now(request.user, uploaded_file)
        messages.success(request, 'Contacts were successfully added.')
    return redirect('myApp:contact_list')


def import_now(user, uploaded_file):
    encoded_file = TextIOWrapper(uploaded_file, encoding='utf-8')
    reader = csv.DictReader(encoded_file)
    for row in reader:
        name = row['name']
        phone_number = row['phone_number']
        email = row['email']
        address = row['address']
        if not Contact.objects.filter(phone_number=phone_number, author=user).exists():
            Contact.objects.create(name=name,
                                    phone_number=phone_number,
                                    email=email,
                                    address=address,
                                    author=user)


# -----------GOOGLE CONTACT-------------


def authorize(request):
    authorization_url, _ = get_google_authorization_url(REDIRECT_URI)
    return redirect(authorization_url)


def oauth2callback(request):
    state = request.GET.get('state')
    code = request.GET.get('code')
    handle_callback_and_googleauth(request, state, code, REDIRECT_URI)
    return redirect('myApp:google_contacts')


def get_google_contacts(request):
    google_auth = get_googleauth_or_authorize(request)
    if isinstance(google_auth, HttpResponseRedirect):
        return google_auth
    contacts = create_google_credentials(google_auth)
    return render(request, 'myApp/google_contacts.html', {'contacts': contacts})


def add_contact_from_google(request, pk):
    google_auth = get_googleauth_or_authorize(request)
    if isinstance(google_auth, HttpResponseRedirect):
        return google_auth

    pk = f'people/{pk}'

    creds = Credentials(
        token=google_auth.access_token,
        refresh_token=google_auth.refresh_token,
        token_uri=google_auth.token_uri,
        client_id=google_auth.client_id,
        client_secret=google_auth.client_secret,
        scopes=google_auth.scopes.split(','),
    )

    service = build('people', 'v1', credentials=creds)

    # Fetch a single contact by resourceName (e.g., 'people/c123456')
    contact = service.people().get(
        resourceName=pk,
        personFields='names,emailAddresses,phoneNumbers,addresses'
    ).execute()

    name = contact['names'][0]['displayName'] if 'names' in contact else ''
    phone_number = contact['phoneNumbers'][0]['value'] if 'phoneNumbers' in contact else ''
    email = contact['emailAddresses'][0]['value'] if 'emailAddresses' in contact else ''
    address = contact['addresses'][0]['formattedValue'] if 'addresses' in contact else ''

    if phone_number and not Contact.objects.filter(phone_number=phone_number, author=request.user).exists():
        Contact.objects.create(
            name=name,
            phone_number=phone_number,
            email=email,
            address=address,
            author=request.user
        )
    return redirect('myApp:contact_list')


def add_contact_in_google(request, pk):
    contact = get_object_or_404(Contact, pk=pk)

    google_auth = get_googleauth_or_authorize(request)
    if isinstance(google_auth, HttpResponseRedirect):
        return google_auth
    creds = Credentials(
        token=google_auth.access_token,
        refresh_token=google_auth.refresh_token,
        token_uri=google_auth.token_uri,
        client_id=google_auth.client_id,
        client_secret=google_auth.client_secret,
        scopes=google_auth.scopes.split(','),
    )
    service = build('people', 'v1', credentials=creds)

    contact_body = {}
    if contact.name:
        contact_body['names'] = [{'givenName': contact.name}]
    if contact.phone_number:
        contact_body['phoneNumbers'] = [{'value': str(contact.phone_number)}]
    if contact.address:
        contact_body['addresses'] = [{'formattedValue': contact.address}]
    if contact.email:
        contact_body['emailAddresses'] = [{'value': contact.email}]

    try:
        service.people().createContact(body=contact_body).execute()
    except Exception as e:
        return HttpResponse(f'Google API error: {e}', status=500)
    return redirect('myApp:google_contacts')


def create_google_credentials(google_auth):
    creds = Credentials(
        token=google_auth.access_token,
        refresh_token=google_auth.refresh_token,
        token_uri=google_auth.token_uri,
        client_id=google_auth.client_id,
        client_secret=google_auth.client_secret,
        scopes=google_auth.scopes.split(','),
    )

    service = build('people', 'v1', credentials=creds)

    results = service.people().connections().list(
        resourceName='people/me',
        pageSize=10,
        personFields='names,emailAddresses,phoneNumbers,addresses'
    ).execute()
    contacts = results.get('connections', [])
    return contacts


def get_google_authorization_url(REDIRECT_URI):
    flow = get_google_flow(REDIRECT_URI)
    state = secrets.token_urlsafe(32)
    temp_user_token = secrets.token_urlsafe(16)
    OAuthState.objects.create(state=state, temp_user_token=temp_user_token)

    authorization_url, _ = flow.authorization_url(
        access_type='offline',
        include_granted_scopes='true',
        prompt='consent',
        state=state
    )
    return authorization_url, temp_user_token


def handle_callback_and_googleauth(request, state, code, REDIRECT_URI):
    if not state or not code:
        return JsonResponse({"error": "Missing state or code."}, status=400)

    try:
        oauth_state = OAuthState.objects.get(state=state)
    except OAuthState.DoesNotExist:
        return JsonResponse({'error': 'Invalid stete.'}, status=400)

myApp/templates/myApp/add_contact.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block content %}
  <div class="container">
    <h2>Add a new Contact</h2>
    <form action="" method="post">
      {% csrf_token %}
      {% bootstrap_form form %}
      <button type="submit" class="btn btn-outline-primary">Add</button>
    </form>
  </div>
{% endblock content %}
  

myApp/templates/myApp/contact_list.html
{% extends 'base.html' %} {% load django_bootstrap5 %} {% block content %}
<div class="container py-5">
  <!-- Header and Actions -->
  <div class="d-flex flex-column flex-md-row align-items-start align-items-md-center justify-content-between mb-4">
    <h2 class="mb-3 mb-md-0">Contacts Directory</h2>
    <!-- Search Form -->
    <form action="{% url 'myApp:contact_list' %}" method="GET" class="d-flex">
      {% bootstrap_form form %}
      <button type="submit" class="btn btn-outline-secondary ms-2 mt-4 mb-3">Search</button>
    </form>
  </div>

  {% if not contacts %}
  <p class="text-danger mt-3">No contacts found.</p>
  {% endif %}

  <table class="table table-dark table-hover">
    <thead>
      <tr>
        <th scope="col">Name</th>
        <th scope="col">Phone Number</th>
        <th scope="col">Email</th>
        <th scope="col">Address</th>
        <th scope="col">Google</th>
        <th scope="col">Edit</th>
        <th scope="col">Delete</th>
      </tr>
    </thead>
    <tbody>
      {% for contact in contacts %}
      <tr>
        <td>{{ contact.name }}</td>
        <td>{{ contact.phone_number }}</td>
        <td>{{ contact.email }}</td>
        <td>{{ contact.address }}</td>
        <td>
          <a
            href="{% url 'myApp:add_contact_in_google' contact.pk%}"
            class="btn btn-outline-success btn-sm"
            >Add</a
          >
        </td>
        <td>
          <a
            href="{% url 'myApp:edit_contact' contact.pk %}"
            class="btn btn-outline-warning btn-sm"
            >Edit</a
          >
        </td>
        <td>
          <a
            href="{% url 'myApp:delete_contact' contact.pk %}"
            class="btn btn-outline-danger btn-sm"
            >Delete</a
          >
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>

  <div class="row g-4">
    <div class="col-md-6">
      <div class="card h-100 shadow-sm">
        <div class="card-body d-flex flex-column justify-content-center text-center">
          <h5 class="card-title">Import Contacts</h5>
          <p class="card-text text-muted">Upload a CSV file to add new contacts.</p>
          <form action="{% url 'myApp:import_contacts' %}" method="post" enctype="multipart/form-data" class="mt-auto">
            {% csrf_token %}
            <input type="file" name="my_file" class="form-control mb-3" />
            <button class="btn btn-warning w-100" type="submit">
              <i class="bi bi-file-earmark-arrow-up"></i> Import CSV
            </button>
          </form>
        </div>
      </div>
    </div>
    <div class="col-md-6">
      <div class="card h-100 shadow-sm">
        <div class="card-body d-flex flex-column justify-content-center text-center">
          <h5 class="card-title">Export Contacts</h5>
          <p class="card-text text-muted">Download your contacts as a CSV file.</p>
          <a href="{% url 'myApp:export_contacts' %}" class="btn btn-success w-100 mt-auto">
            <i class="bi bi-file-earmark-arrow-down"></i> Export CSV
          </a>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

myApp/templates/myApp/delete_contact.html
{% extends 'base.html' %}

{% block content %}
  <div class="container">
    <h2>Are you really sure you want to delete "{{contact.name}}" contact?</h2>
    <form action="" method="post">
      {% csrf_token %}
      <button type="submit" class="btn btn-danger">Delete</button>
      <a href="{% url 'myApp:contact_list' %}" class="btn btn-secondary">Cancel</a>
    </form>
  </div>
{% endblock content %}
  

myApp/templates/myApp/edit_contact.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block content %}
  <div class="container">
    <h2>Edit your Contact</h2>
    <form action="" method="post">
      {% csrf_token %}
      {% bootstrap_form form %}
      <button type="submit" class="btn btn-outline-primary">Update</button>
    </form>
  </div>
{% endblock content %}
  

myApp/templates/myApp/google_contacts.html
{% extends 'base.html' %} {% load django_bootstrap5 %} {% block content %}
<div class="container py-5">

  <h2 class="mb-4">List of contacts from Google Contact:</h2>
  {% if not contacts %}
  <p class="text-danger mt-3">No contacts found.</p>
  {% endif %}

  <table class="table table-dark table-hover">
    <thead>
      <tr>
        <th scope="col">Name</th>
        <th scope="col">Phone Number</th>
        <th scope="col">Email</th>
        <th scope="col">Address</th>
        <th scope="col">Add to DB</th>
      </tr>
    </thead>
    <tbody>
      {% for contact in contacts %}
      <tr>
        <td>{{ contact.names.0.displayName }}</td>
        <td>{{ contact.phoneNumbers.0.value }}</td>
        <td>{{ contact.emailAddresses.0.value }}</td>
        <td>{{ contact.addresses.0.formattedValue }}</td>
        </td>
        <td>
          <a
            href="{% url 'myApp:add_from_google' pk=contact.resourceName|cut:'people/' %}"
            class="btn btn-outline-warning btn-sm"
            >Add</a
          >
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>

  
</div>
{% endblock content %}

myApp/templates/myApp/index.html
{% extends 'base.html' %}

{% block content %}
  <div class="container">
    <h1>Welcome!</h1>
  </div>
{% endblock content %}
  